import axios from "axios";

const BACKEND_URL =
  "https://rnexpensetracker-a4690-default-rtdb.firebaseio.com";

export async function storeExpense(expenseData) {
  //the .json is a firebase specific
  const response = await axios.post(
    BACKEND_URL + "/expenses.json",
    expenseData
  );
  //when we want to access the id generated by firebase, we will access:
  const id = response.data.name;
  //notice that the uniqe id is not called "id" in firebase but "name"
  return id;
}

export async function fetchExpenses() {
  const response = await axios.get(BACKEND_URL + "/expenses.json");

  const expenses = [];

  for (const key in response.data) {
    const expenseObj = {
      id: key,
      amount: response.data[key].amount,
      date: new Date(response.data[key].date),
      description: response.data[key].description,
    };
    expenses.push(expenseObj);
  }
  return expenses;
}

export function updateExpense(id, expenseData) {
  return axios.put(BACKEND_URL + `/expenses/${id}.json`, expenseData);
}

export function deleteExpense(id) {
  return axios.delete(BACKEND_URL + `/expenses/${id}.json`);
}
